name: Create Release

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main ]
#on:
#  push:
#    tags:
#      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
#  build_phone_and_wear_app:
#    name: "Build phone and wear app"
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Setup JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'zulu'
#          java-version: '17'
#
#      - name: Generate Release bundles
#        run: ./gradlew bundleRelease
#
#      - name: Sign phone bundle
#        uses: r0adkll/sign-android-release@v1
#        id: sign_phone_app
#        with:
#          releaseDirectory: app/build/outputs/bundle/release
#          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
#          alias: ${{ secrets.ALIAS }}
#          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
#          keyPassword: ${{ secrets.KEY_PASSWORD }}
#
#      - name: Sign wear bundle
#        uses: r0adkll/sign-android-release@v1
#        id: sign_wear_app
#        with:
#          releaseDirectory: wearos/build/outputs/bundle/release
#          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
#          alias: ${{ secrets.ALIAS }}
#          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
#          keyPassword: ${{ secrets.KEY_PASSWORD }}
#
#      - name: Publish phone app to Play Console
#        uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJsonPlainText: ${{ secrets.PLAY_CONSOLE_SERVICE_ACCOUNT_JSON }}
#          packageName: com.ramitsuri.notificationjournal
#          releaseFiles: app/build/outputs/bundle/release/app-release.aab
#          track: internal
#          status: completed
#
#      - name: Publish wear OS app to Play Console
#        uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJsonPlainText: ${{ secrets.PLAY_CONSOLE_SERVICE_ACCOUNT_JSON }}
#          packageName: com.ramitsuri.notificationjournal
#          releaseFiles: wearos/build/outputs/bundle/release/wearos-release.aab
#          track: wear:internal
#          status: completed

  build_desktop_app:
    name: "Build desktop app"
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Generate package
        run: ./gradlew packageDistributionForCurrentOS

      - name: Create github release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            core/build/compose/binaries/main/dmg/com.ramitsuri.notificationjournal.desktop-1.0.0.dmg